[package]
name = "ai_simulation_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
uuid = { version = "1.8.0", features = ["v4"] }
rayon = "1.10.0"
bevy = "0.10"
bevy_egui = "0.20"